// <auto-generated />
using System;
using MAuthen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAuthen.Data.Migrations
{
    [DbContext(typeof(MAuthenContext))]
    [Migration("20191119185412_ChangeDatabase")]
    partial class ChangeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAuthen.Domain.Entities.ContactEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContactsId");

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.HasIndex("ContactsId");

                    b.ToTable("ContactEmail");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContactsId");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("ContactsId");

                    b.ToTable("ContactPhone");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.Contacts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdUser");

                    b.Property<string>("Password");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("TotpSecret");

                    b.HasKey("Id");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Certificate");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Domain");

                    b.Property<bool>("HasTotp");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasFilter("[Domain] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<bool>("Blocked");

                    b.Property<DateTime>("BlockedTime");

                    b.Property<string>("FirstName");

                    b.Property<bool>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.UserServiceRoles", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("ServiceId");

                    b.Property<DateTime>("CreatedOn");

                    b.HasKey("UserId", "RoleId", "ServiceId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServiceId");

                    b.ToTable("UserServiceRoles");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.ContactEmail", b =>
                {
                    b.HasOne("MAuthen.Domain.Entities.Contacts")
                        .WithMany("Email")
                        .HasForeignKey("ContactsId");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.ContactPhone", b =>
                {
                    b.HasOne("MAuthen.Domain.Entities.Contacts")
                        .WithMany("Phone")
                        .HasForeignKey("ContactsId");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.Contacts", b =>
                {
                    b.HasOne("MAuthen.Domain.Entities.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.Secret", b =>
                {
                    b.HasOne("MAuthen.Domain.Entities.User", "User")
                        .WithOne("Secret")
                        .HasForeignKey("MAuthen.Domain.Entities.Secret", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MAuthen.Domain.Entities.UserServiceRoles", b =>
                {
                    b.HasOne("MAuthen.Domain.Entities.Role", "Role")
                        .WithMany("UserServiceRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MAuthen.Domain.Entities.Service", "Service")
                        .WithMany("UserServicesRoles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MAuthen.Domain.Entities.User", "User")
                        .WithMany("UserServiceRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
